# Copyright 2023 Logan Magee
#
# SPDX-License-Identifier: AGPL-3.0-only

permissions: {}

name: CI

on: [push, pull_request]

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          check-latest: true
          cache: npm
      - run: npm install -g @angular/cli && npm ci && ng build
      - run: ng lint
