# Copyright 2025 Logan Magee
#
# SPDX-License-Identifier: AGPL-3.0-only

name: Deploy Accrescent console

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 22
          check-latest: true
          cache: npm
      - run: npm install -g @angular/cli && npm ci && ng build
      - uses: cloudflare/wrangler-action@v3
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          wranglerVersion: "latest"
